site_name: OSG Technology Area
site_url: https://osg-htc.org/technology/
repo_url: https://github.com/osg-htc/technology/
theme:
  name: material
  custom_dir: osgthedocs
  favicon: img/favicon.ico

extra_css:
  - css/extra.css

nav:
  - Home: 'index.md'
  - Software:
    - Packaging:
      - RPM Development Guide: 'software/rpm-development-guide.md'
      - OSG Build Tools: 'software/osg-build-tools.md'
      - Using Quilt: 'software/quilt.md'
      - Upcoming to Main: 'software/upcoming-to-main.md'
      - Koji Workflow: 'software/koji-workflow.md'
      - Creating the VO Client Package: 'software/create-vo-client.md'
      - Container Development Guide: 'software/container-development-guide.md'
      - Repository Management: 'software/repository-management.md'
      - Globus Mass Update Procedure: 'software/globus-mass-update-procedure.md'
      - Resurrecting Epel Packages: 'software/resurrecting-epel-packages.md'
      - Koji Mass Rebuilds: 'software/koji-mass-rebuilds.md'
    - Development:
      - Development Process: 'software/development-process.md'
      - Git Software Development Process: 'software/git-software-development.md'
      - CE Scale Testing: 'software/ce-test-scaling.md'
      - IPv6 Testing: 'software/ipv6-testing.md'
      - How to Request Tokens: 'software/requesting-tokens.md'
    - Software Support: 'policy/software-support.md'
    - Effort Tracking: 'software/effort-tracking.md'
    - Release Planning: 'software/release-planning.md'
    - New Team Member: 'software/new-team-member.md'
  - Release:
    - How to Cut a Release: 'release/cut-sw-release.md'
    - How to Cut a Data Release: 'release/cut-data-release.md'
    - Ready for Testing Announcements: 'release/announce-rft-packages.md'
    - New Release Series: 'release/new-release-series.md'
    - Old Release Series Removal: 'release/old-release-removal.md'
    - ITB Prerelease Testing: 'release/itb-testing.md'
    - Empty Packages: 'release/empty-pkgs.md'
    - Acceptance Testing: 'release/acceptance-testing.md'
  - Policy:
    - GridFTP and GSI Migration: 'policy/gridftp-gsi-migration.md'
    - Campus Cyberinfrastructure: 'policy/campus-cyberinfrastructure.md'
    - Collaborations and Bearer Tokens: 'policy/collab-bearer-tokens.md'
    - CREAM-CE Support: 'policy/cream-support.md'
    - 'Release Series Support': 'policy/release-series.md'
    - 'Globus Toolkit Support': 'policy/globus-toolkit.md'
    - 'OASIS Repository Mirroring': 'policy/external-oasis-repos.md'
    - 'Flexible Release Model': 'policy/flexible-release-model.md'
    - Software Release Policy: 'policy/software-release.md'
    - Container Release Policy: 'policy/container-release.md'
    - 'Community Testing': 'policy/community-testing.md'
    - Registering with the OSG: 'policy/comanage-instructions-user.md'
    - New OSPool User Registration: 'policy/new-ospool-user.md'
    - Approving COManage Registrations: 'policy/comanage-instructions-admin.md'
    - Handling Topology/Contacts Registrations: 'policy/topology-registration.md'
  - Documentation:
    - Writing Documentation: 'documentation/writing-documentation.md'
    - Reviewing Documentation: 'documentation/reviewing-documentation.md'
    - Markdown Style Guide: 'documentation/style-guide.md'
    - Publishing OSG pages: 'documentation/publish-osg-pages.md'
  - Historical Transitions:
    - Service Migrations - Spring 2018: 'policy/service-migrations-spring-2018.md'
    - GUMS Retirement: 'policy/gums-retire.md'
    - BeStMan2 Retirement: 'policy/bestman2-retire.md'
    - VOMS Admin Retirement: 'policy/voms-admin-retire.md'
    - SHA-2 Support: 'projects/sha2-support.md'
    - Migrating Documents to Markdown: 'documentation/markdown-migration.md'
  - Meetings:
    - September 20, 2022: 'meetings/2022/TechArea20220920.md'
    - September 13, 2022: 'meetings/2022/TechArea20220913.md'
    - September 6, 2022: 'meetings/2022/TechArea20220906.md'
    - August 30, 2022: 'meetings/2022/TechArea20220830.md'
    - August 23, 2022: 'meetings/2022/TechArea20220823.md'
    - August 16, 2022: 'meetings/2022/TechArea20220816.md'
    - August 9, 2022: 'meetings/2022/TechArea20220809.md'
    - August 2, 2022: 'meetings/2022/TechArea20220802.md'
    - July 26, 2022: 'meetings/2022/TechArea20220726.md'
    - June 28, 2022: 'meetings/2022/TechArea20220628.md'
    - June 21, 2022: 'meetings/2022/TechArea20220621.md'
    - June 7, 2022: 'meetings/2022/TechArea20220607.md'
    - May 31, 2022: 'meetings/2022/TechArea20220531.md'
    - May 10, 2022: 'meetings/2022/TechArea20220510.md'
    - May 3, 2022: 'meetings/2022/TechArea20220503.md'
    - April 26, 2022: 'meetings/2022/TechArea20220426.md'
    - April 19, 2022: 'meetings/2022/TechArea20220419.md'
    - April 5, 2022: 'meetings/2022/TechArea20220405.md'
    - March 29, 2022: 'meetings/2022/TechArea20220329.md'
    - March 22, 2022: 'meetings/2022/TechArea20220322.md'
    - March 8, 2022: 'meetings/2022/TechArea20220308.md'
    - March 1, 2022: 'meetings/2022/TechArea20220301.md'
    - February 22, 2022: 'meetings/2022/TechArea20220222.md'
    - February 8, 2022: 'meetings/2022/TechArea20220208.md'
    - February 1, 2022: 'meetings/2022/TechArea20220201.md'
    - January 25, 2022: 'meetings/2022/TechArea20220125.md'
    - January 18, 2022: 'meetings/2022/TechArea20220118.md'
    - January 11, 2022: 'meetings/2022/TechArea20220111.md'
    - January 4, 2022: 'meetings/2022/TechArea20220104.md'
    - December 14, 2021: 'meetings/2021/TechArea20211214.md'
    - December 7, 2021: 'meetings/2021/TechArea20211207.md'
    - November 30, 2021: 'meetings/2021/TechArea20211130.md'
    - November 23, 2021: 'meetings/2021/TechArea20211123.md'
    - November 16, 2021: 'meetings/2021/TechArea20211116.md'
    - November 9, 2021: 'meetings/2021/TechArea20211109.md'
    - November 2, 2021: 'meetings/2021/TechArea20211102.md'
    - October 26, 2021: 'meetings/2021/TechArea20211026.md'
    - October 19, 2021: 'meetings/2021/TechArea20211019.md'
    - October 12, 2021: 'meetings/2021/TechArea20211012.md'
    - October 5, 2021: 'meetings/2021/TechArea20211005.md'
    - September 28, 2021: 'meetings/2021/TechArea20210928.md'
    - September 14, 2021: 'meetings/2021/TechArea20210914.md'
    - September 7, 2021: 'meetings/2021/TechArea20210907.md'
    - August 31, 2021: 'meetings/2021/TechArea20210831.md'
    - August 24, 2021: 'meetings/2021/TechArea20210824.md'
    - August 17, 2021: 'meetings/2021/TechArea20210817.md'
    - August 10, 2021: 'meetings/2021/TechArea20210810.md'
    - August 3, 2021: 'meetings/2021/TechArea20210803.md'
    - July 27, 2021: 'meetings/2021/TechArea20210727.md'
    - July 20, 2021: 'meetings/2021/TechArea20210720.md'
    - July 13, 2021: 'meetings/2021/TechArea20210713.md'
    - July 6, 2021: 'meetings/2021/TechArea20210706.md'
    - June 29, 2021: 'meetings/2021/TechArea20210629.md'
    - June 22, 2021: 'meetings/2021/TechArea20210622.md'
    - June 15, 2021: 'meetings/2021/TechArea20210615.md'
    - June 8, 2021: 'meetings/2021/TechArea20210608.md'
    - May 18, 2021: 'meetings/2021/TechArea20210518.md'
    - May 11, 2021: 'meetings/2021/TechArea20210511.md'
    - May 4, 2021: 'meetings/2021/TechArea20210504.md'
    - April 20, 2021: 'meetings/2021/TechArea20210420.md'
    - April 13, 2021: 'meetings/2021/TechArea20210413.md'
    - April 6, 2021: 'meetings/2021/TechArea20210406.md'
    - March 30, 2021: 'meetings/2021/TechArea20210330.md'
    - March 23, 2021: 'meetings/2021/TechArea20210323.md'
    - March 9, 2021: 'meetings/2021/TechArea20210309.md'
    - March 2, 2021: 'meetings/2021/TechArea20210302.md'
    - February 23, 2021: 'meetings/2021/TechArea20210223.md'
    - February 16, 2021: 'meetings/2021/TechArea20210216.md'
    - February 9, 2021: 'meetings/2021/TechArea20210209.md'
    - February 2, 2021: 'meetings/2021/TechArea20210202.md'
    - January 26, 2021: 'meetings/2021/TechArea20210126.md'
    - January 19, 2021: 'meetings/2021/TechArea20210119.md'
    - January 12, 2021: 'meetings/2021/TechArea20210112.md'
    - January 4, 2021: 'meetings/2021/TechArea20210104.md'
    - December 21, 2020: 'meetings/2020/TechArea20201221.md'
    - December 14, 2020: 'meetings/2020/TechArea20201214.md'
    - December 7, 2020: 'meetings/2020/TechArea20201207.md'
    - November 30, 2020: 'meetings/2020/TechArea20201130.md'
    - November 23, 2020: 'meetings/2020/TechArea20201123.md'
    - November 16, 2020: 'meetings/2020/TechArea20201116.md'
    - November 9, 2020: 'meetings/2020/TechArea20201109.md'
    - November 2, 2020: 'meetings/2020/TechArea20201102.md'
    - October 26, 2020: 'meetings/2020/TechArea20201026.md'
    - October 19, 2020: 'meetings/2020/TechArea20201019.md'
    - October 12, 2020: 'meetings/2020/TechArea20201012.md'
    - October 5, 2020: 'meetings/2020/TechArea20201005.md'
    - September 28, 2020: 'meetings/2020/TechArea20200928.md'
    - September 14, 2020: 'meetings/2020/TechArea20200914.md'
    - August 24, 2020: 'meetings/2020/TechArea20200824.md'
    - August 17, 2020: 'meetings/2020/TechArea20200817.md'
    - August 10, 2020: 'meetings/2020/TechArea20200810.md'
    - August 3, 2020: 'meetings/2020/TechArea20200803.md'
    - July 27, 2020: 'meetings/2020/TechArea20200727.md'
    - July 20, 2020: 'meetings/2020/TechArea20200720.md'
    - July 13, 2020: 'meetings/2020/TechArea20200713.md'
    - July 6, 2020: 'meetings/2020/TechArea20200706.md'
    - June 29, 2020: 'meetings/2020/TechArea20200629.md'
    - June 22, 2020: 'meetings/2020/TechArea20200622.md'
    - June 15, 2020: 'meetings/2020/TechArea20200615.md'
    - June 8, 2020: 'meetings/2020/TechArea20200608.md'
    - June 1, 2020: 'meetings/2020/TechArea20200601.md'
    - May 18, 2020: 'meetings/2020/TechArea20200518.md'
    - May 11, 2020: 'meetings/2020/TechArea20200511.md'
    - May 4, 2020: 'meetings/2020/TechArea20200504.md'
    - April 27, 2020: 'meetings/2020/TechArea20200427.md'
    - April 20, 2020: 'meetings/2020/TechArea20200420.md'
    - April 13, 2020: 'meetings/2020/TechArea20200413.md'
    - April 6, 2020: 'meetings/2020/TechArea20200406.md'
    - March 30, 2020: 'meetings/2020/TechArea20200330.md'
    - March 23, 2020: 'meetings/2020/TechArea20200323.md'
    - March 16, 2020: 'meetings/2020/TechArea20200316.md'
    - March 9, 2020: 'meetings/2020/TechArea20200309.md'
    - March 2, 2020: 'meetings/2020/TechArea20200302.md'
    - February 24, 2020: 'meetings/2020/TechArea20200224.md'
    - February 17, 2020: 'meetings/2020/TechArea20200217.md'
    - February 10, 2020: 'meetings/2020/TechArea20200210.md'
    - February 3, 2020: 'meetings/2020/TechArea20200203.md'
    - January, 27 2020: 'meetings/2020/TechArea20200127.md'
    - January, 13 2020: 'meetings/2020/TechArea20200113.md'
    - January, 6 2020: 'meetings/2020/TechArea20200106.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - toc:
      permalink: True

